% Get the result from the lkh algorythm for solving the tsp
waypoint_name = waypoints;
wp_name = 'wp_opt';

% Export the tsp file from the waypoints generated by the algorythm
tspExportFnc(waypoint_name, 'LKH-2.0.10/wp_opt', true);

% Define the path to the LKH executable
lkh_executable = '/home/clem/matlab_irp/LKH-2.0.10/LKH';

% Define the directory where the parameter file is located
param_file_directory = '/home/clem/matlab_irp/LKH-2.0.10';

% Define the full path to the parameter file
parameter_file = fullfile(param_file_directory, 'wp_opt.par');

% Check if the parameter file exists
if ~isfile(parameter_file)
    error('Parameter file does not exist: %s', parameter_file);
end

% Change MATLAB's current working directory to the parameter file directory
original_directory = pwd; % Save the original directory
cd(param_file_directory);

% Construct the command to run LKH with the parameter file
command = sprintf('%s %s', lkh_executable, 'wp_opt.par');

% Run the command in the system shell
[status, cmdout] = system(command);

% Restore the original directory
cd(original_directory);

% Check if the command was successful
if status == 0
    fprintf('LKH solver executed successfully.\n');
    disp(cmdout); % Display the output from the command
else
    error('Failed to execute LKH solver. Command output:\n%s', cmdout);
end

wp_opt_lkh = tspSolReadFnc(waypoint_name, 'LKH-2.0.10/wp_opt_sol.tsp');


